# 已部署的gitlab runner 无法直接使用 docker hub
# 所以需要使用其他的docker镜像源
# 关于使用的镜像仓库的说明：
# https://github.com/DaoCloud/public-image-mirror
# 关于webhook的用法：
# https://docs.gitlab.com/ee/ci/triggers/#use-a-webhook
# gitlab ci里可用的预定义变量
# https://docs.gitlab.com/ee/ci/variables/predefined_variables.html#predefined-variables
# https://docs.gitlab.com/ee/ci/variables/index.html
stages:
  - rotate_access_token
  - auto_archiving
  - check_config

include:
  - local: "/.gitlab/workflows/AutoArchiving.yml"
  - local: "/.gitlab/workflows/RotateAccessToken.yml"
  - local: "/.gitlab/workflows/CheckConfig.yml"
    